### ISSUE TITLE
Package does not build under Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by MatiMax** [rhx/SwiftLibXML#1]
The package does not build due to the following error:

```
/usr/include/xlocale.h:27:16: error: redefinition of '__locale_struct'
~/gir2swift/.build/checkouts/SwiftLibXML.git--3298132882809410232/Sources/XMLDocument.swift:14:8: error: could not build Objective-C module 'CLibXML2'
```
The latest version of `libxml2-dev` is installed:

```
sudo apt install libxml2-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxml2-dev is already the newest version (2.9.3+dfsg1-1ubuntu0.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by rhx** [comment]
Just tried this with Swift 5 on the latest 16.04.6 LTS, and it worked for me.  Can you let me know if this is still an issue you are seeing?

[Edit: version is 16.04.6 LTS not 16.04.4]

**Comment by rhx** [comment]
Closing this as Swift 16.04.x LTS is now EOL, but there are CI scripts for newer LTS versions now.
